{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "label_names()" } }
  ]
 },
 "panels": [
  {
   "title": "Free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(rate(node_disk_writes_completed_total{instance=\"localhost:9100\",job=\"node\"}[1m]) + rate(node_disk_reads_completed_total{instance=\"localhost:9100\",job=\"node\"}[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node\",instance=\"localhost:9100\",mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}